"""Export a real, model-scored timeline for the demo page.

The demo page does not simulate the classifier in JavaScript. It plays back
the actual softmax output this model produced on a track it has never seen,
window by window. This script writes that recording.
"""

import json
import os
import sys

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, os.path.join(ROOT, "ml"))
sys.path.insert(0, os.path.join(ROOT, "simulator"))

from simulate_collar import (CLASSES, SAMPLE_SECONDS, SAMPLES_PER_DAY, WINDOW,
                             plan_herd_drives, simulate_animal,
                             simulate_herd_centroid, apply_sensor_noise,
                             window_label)
from proteus_bridge import WindowBuilder, classify, load_model


def find_track(days=4, tries=60):
    """Look for a track that actually contains all three abnormal events, so
    the demo shows the system working rather than a quiet afternoon."""
    n = days * SAMPLES_PER_DAY
    best = None
    for seed in range(1000, 1000 + tries):
        rng = np.random.default_rng(seed)
        drive = plan_herd_drives(n, rng)
        herd = simulate_herd_centroid(n, rng, drive=drive)
        lat, lon, temp, hr, labels, _ = simulate_animal(n, herd, rng, drive=drive)
        counts = {c: int((labels == i).sum()) for i, c in enumerate(CLASSES)}
        score = min(counts["illness_suspect"], 120) + \
            min(counts["theft_suspect"], 40) * 3 + \
            min(counts["predator_flight"], 8) * 10
        if counts["illness_suspect"] and counts["theft_suspect"] and counts["predator_flight"]:
            if best is None or score > best[0]:
                lat2, lon2, temp2, hr2 = apply_sensor_noise(lat, lon, temp, hr, rng)
                best = (score, seed, lat2, lon2, temp2, hr2, labels, herd, drive)
    return best


def main():
    found = find_track()
    if found is None:
        raise SystemExit("no track with all three event types; widen the search")
    score, seed, lat, lon, temp, hr, labels, herd, drive = found
    print(f"using seed {seed} (event score {score}), {len(lat)} samples")

    net, mu, sd, classes = load_model()
    wb = WindowBuilder()
    frames = []
    stride = 3

    for i in range(len(lat)):
        breached = wb.push(float(lat[i]), float(lon[i]), float(temp[i]),
                           float(hr[i]), i, float(herd[i, 0]), float(herd[i, 1]))
        if not wb.ready() or i % stride:
            continue
        X = wb.array()
        pred, prob, probs = classify(net, mu, sd, classes, X)
        row = X[0]
        hour = (i % SAMPLES_PER_DAY) * SAMPLE_SECONDS / 3600.0
        frames.append({
            "t": i,
            "day": i // SAMPLES_PER_DAY + 1,
            "hour": round(hour, 2),
            "speed": round(float(row[0, -1]), 3),
            "herd_dist": round(float(row[3, -1]), 1),
            "fence_dist": round(float(row[4, -1]), 1),
            "temp": round(float(row[5, -1]), 2),
            "hr": round(float(row[6, -1]), 1),
            "breached": bool(breached),
            "pred": pred,
            "probs": [round(float(p), 4) for p in probs],
            # Window-level truth, using the same rule the training set used.
            # Comparing a window prediction against the label of its final
            # sample would understate agreement for no good reason.
            "truth": CLASSES[window_label(labels[i - WINDOW + 1:i + 1])],
        })

    out = {
        "note": ("Real softmax output from ml/artifacts/smartherd_cnn_gru.pt on a "
                 "track it was not trained on. Generated by "
                 "demo/export_timeline.py; not hand-edited."),
        "seed": seed,
        "classes": classes,
        "sample_seconds": SAMPLE_SECONDS,
        "window": WINDOW,
        "stride": stride,
        "frames": frames,
    }
    path = os.path.join(HERE, "timeline.json")
    with open(path, "w") as f:
        json.dump(out, f, separators=(",", ":"))

    agree = sum(1 for f in frames if f["pred"] == f["truth"])
    print(f"{len(frames)} frames, {agree} agree with ground truth "
          f"({agree/len(frames):.1%})")
    seen = {}
    for f in frames:
        seen[f["pred"]] = seen.get(f["pred"], 0) + 1
    print("predictions:", seen)
    print("wrote", path, os.path.getsize(path), "bytes")


if __name__ == "__main__":
    main()
